# The default image to use when user image is missing.
default-image: https://upload.wikimedia.org/wikipedia/commons/c/cd/Portrait_Placeholder_Square.png

collections:
  profile:
    output: true

jekyll-mentions:
    base_url: https://github.com
